---
- name: Setup repository
  yum_repoisitory:
    name: "{{ mssql_repo_name }}"
    description: "{{ mssql_repo_description }}"
    baseurl: "{{ mssql_repo_baseurl }}"
    enabled: "{{ mssql_repo_enabled }}"
    gpg_check: "{{ mssql_repo_gpgcheck }}"

- name: Import GPG key.
  rpm_key:
    key: "{{ mssql_repo_gpg }}"
    state: present
